name: 'acmn_realestate'
version: '1.0.0'
config-version: 2
profile: 'acmn_realestate'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  acmn_realestate:
    silver:
      +materialized: table
      +schema: SILVER
    
    gold:
      +materialized: table
      +schema: GOLD

require-dbt-version: [">=1.0.0", "<2.0.0"]
