CREATE WAREHOUSE IF NOT EXISTS ACMN_REALESTATE_WH 
    WITH WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;

ALTER WAREHOUSE ACMN_REALESTATE_WH RESUME IF SUSPENDED;

CREATE DATABASE IF NOT EXISTS ACMN_REALESTATE_DB;

CREATE SCHEMA IF NOT EXISTS ACMN_REALESTATE_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS ACMN_REALESTATE_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS ACMN_REALESTATE_DB.GOLD;

CREATE ROLE IF NOT EXISTS ACMN_PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE ACMN_REALESTATE_WH TO ROLE ACMN_PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON DATABASE ACMN_REALESTATE_DB TO ROLE ACMN_PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ACMN_REALESTATE_DB TO ROLE ACMN_PIPELINE_ROLE;

CREATE USER IF NOT EXISTS acmn_pipeline_user 
    PASSWORD = 'pipeline_password' 
    DEFAULT_ROLE = ACMN_PIPELINE_ROLE 
    DEFAULT_WAREHOUSE = ACMN_REALESTATE_WH 
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE ACMN_PIPELINE_ROLE TO USER acmn_pipeline_user;
